-- Loan Dashboard: initial schema for loans and reserves
-- Run this in Supabase SQL Editor or via Supabase CLI (supabase db push)

-- Loans table
CREATE TABLE IF NOT EXISTS public.loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client TEXT NOT NULL,
  ref TEXT,
  total NUMERIC(14, 2) NOT NULL,
  installment NUMERIC(14, 2) NOT NULL,
  paid_count INT NOT NULL DEFAULT 0,
  total_installments INT NOT NULL,
  start_date DATE NOT NULL,
  freq_days INT NOT NULL DEFAULT 7,
  payment_dates JSONB NOT NULL DEFAULT '[]',
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Reserves table
CREATE TABLE IF NOT EXISTS public.reserves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client TEXT NOT NULL,
  amount NUMERIC(14, 2) NOT NULL,
  installments INT NOT NULL DEFAULT 1,
  "date" DATE NOT NULL,
  freq_days INT NOT NULL DEFAULT 7,
  note TEXT,
  paid_count INT NOT NULL DEFAULT 0,
  deduction_dates JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Optional: updated_at trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- EXECUTE FUNCTION is PostgreSQL 11+; use EXECUTE PROCEDURE on older versions
CREATE TRIGGER loans_updated_at
  BEFORE UPDATE ON public.loans
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER reserves_updated_at
  BEFORE UPDATE ON public.reserves
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Row Level Security: allow anon/authenticated to read and write (no auth in app yet)
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reserves ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on loans"
  ON public.loans FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow all on reserves"
  ON public.reserves FOR ALL
  USING (true)
  WITH CHECK (true);

-- Indexes for common filters
CREATE INDEX IF NOT EXISTS idx_loans_paid_count ON public.loans (paid_count);
CREATE INDEX IF NOT EXISTS idx_loans_start_date ON public.loans (start_date);
CREATE INDEX IF NOT EXISTS idx_reserves_paid_count ON public.reserves (paid_count);
CREATE INDEX IF NOT EXISTS idx_reserves_date ON public.reserves ("date");
