-- Client Insurance: client name, MC number, status (OK, inactive, cancellation, expiration date).
-- Self-contained: does not depend on team_members or 002. Policies use owner_id only.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS public.client_insurance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  client TEXT NOT NULL,
  mc TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'OK',
  expiration_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_client_insurance_owner_id ON public.client_insurance (owner_id);
CREATE INDEX IF NOT EXISTS idx_client_insurance_status ON public.client_insurance (status);
CREATE INDEX IF NOT EXISTS idx_client_insurance_expiration_date ON public.client_insurance (expiration_date);

CREATE TRIGGER client_insurance_updated_at
  BEFORE UPDATE ON public.client_insurance
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.client_insurance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "client_insurance_select" ON public.client_insurance FOR SELECT
  USING (owner_id = auth.uid() OR owner_id IS NULL);

CREATE POLICY "client_insurance_insert" ON public.client_insurance FOR INSERT
  WITH CHECK (owner_id = auth.uid() OR owner_id IS NULL);

CREATE POLICY "client_insurance_update" ON public.client_insurance FOR UPDATE
  USING (owner_id = auth.uid() OR owner_id IS NULL)
  WITH CHECK (true);

CREATE POLICY "client_insurance_delete" ON public.client_insurance FOR DELETE
  USING (owner_id = auth.uid() OR owner_id IS NULL);
