-- Single row per owner: when client insurance was last verified and by whom.
-- Checked weekly; Overview shows warning if older than 7 days.

CREATE TABLE IF NOT EXISTS public.insurance_verification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  last_checked_date DATE,
  checked_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (owner_id)
);

CREATE INDEX IF NOT EXISTS idx_insurance_verification_owner_id ON public.insurance_verification (owner_id);

CREATE TRIGGER insurance_verification_updated_at
  BEFORE UPDATE ON public.insurance_verification
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.insurance_verification ENABLE ROW LEVEL SECURITY;

CREATE POLICY "insurance_verification_select" ON public.insurance_verification FOR SELECT
  USING (owner_id = auth.uid());

CREATE POLICY "insurance_verification_insert" ON public.insurance_verification FOR INSERT
  WITH CHECK (owner_id = auth.uid());

CREATE POLICY "insurance_verification_update" ON public.insurance_verification FOR UPDATE
  USING (owner_id = auth.uid())
  WITH CHECK (true);

CREATE POLICY "insurance_verification_delete" ON public.insurance_verification FOR DELETE
  USING (owner_id = auth.uid());
