-- Full cancellation history: one row per time a client was set to cancellation with a date.
-- View all via Audit button in client insurance detail modal.

CREATE TABLE IF NOT EXISTS public.client_insurance_cancellation_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_insurance_id BIGINT NOT NULL REFERENCES public.client_insurance(id) ON DELETE CASCADE,
  cancellation_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cancellation_audit_client_insurance_id
  ON public.client_insurance_cancellation_audit (client_insurance_id);
CREATE INDEX IF NOT EXISTS idx_cancellation_audit_cancellation_date
  ON public.client_insurance_cancellation_audit (cancellation_date);

ALTER TABLE public.client_insurance_cancellation_audit ENABLE ROW LEVEL SECURITY;

-- Allow select/insert only for client_insurance rows the user can access (same owner).
CREATE POLICY "cancellation_audit_select" ON public.client_insurance_cancellation_audit
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.client_insurance ci
      WHERE ci.id = client_insurance_id
        AND (ci.owner_id = auth.uid() OR ci.owner_id IS NULL)
    )
  );

CREATE POLICY "cancellation_audit_insert" ON public.client_insurance_cancellation_audit
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.client_insurance ci
      WHERE ci.id = client_insurance_id
        AND (ci.owner_id = auth.uid() OR ci.owner_id IS NULL)
    )
  );

CREATE POLICY "cancellation_audit_delete" ON public.client_insurance_cancellation_audit
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.client_insurance ci
      WHERE ci.id = client_insurance_id
        AND (ci.owner_id = auth.uid() OR ci.owner_id IS NULL)
    )
  );
