-- AAA Payments: record client payments to AAA entities (Lease, Mega Fuel, Equipment, BJK Fuel).

CREATE TABLE IF NOT EXISTS public.aaa_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  client TEXT NOT NULL,
  payee TEXT NOT NULL,
  amount NUMERIC(14, 2) NOT NULL,
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT aaa_payments_payee_check CHECK (
    payee IN ('AAA Lease', 'AAA Mega Fuel', 'AAA Equipment', 'BJK Fuel')
  )
);

CREATE INDEX IF NOT EXISTS idx_aaa_payments_owner_id ON public.aaa_payments (owner_id);
CREATE INDEX IF NOT EXISTS idx_aaa_payments_payment_date ON public.aaa_payments (payment_date DESC);
CREATE INDEX IF NOT EXISTS idx_aaa_payments_created_at ON public.aaa_payments (created_at DESC);

ALTER TABLE public.aaa_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "aaa_payments_select" ON public.aaa_payments FOR SELECT
  USING (
    owner_id = auth.uid()
    OR owner_id IN (SELECT owner_id FROM public.team_members WHERE member_id = auth.uid())
    OR owner_id IS NULL
  );

CREATE POLICY "aaa_payments_insert" ON public.aaa_payments FOR INSERT
  WITH CHECK (
    owner_id = auth.uid()
    OR owner_id IN (SELECT owner_id FROM public.team_members WHERE member_id = auth.uid())
    OR owner_id IS NULL
  );

CREATE POLICY "aaa_payments_update" ON public.aaa_payments FOR UPDATE
  USING (
    owner_id = auth.uid()
    OR owner_id IN (SELECT owner_id FROM public.team_members WHERE member_id = auth.uid())
    OR owner_id IS NULL
  )
  WITH CHECK (true);

CREATE POLICY "aaa_payments_delete" ON public.aaa_payments FOR DELETE
  USING (
    owner_id = auth.uid()
    OR owner_id IN (SELECT owner_id FROM public.team_members WHERE member_id = auth.uid())
    OR owner_id IS NULL
  );

-- Realtime
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'aaa_payments') THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.aaa_payments;
    EXCEPTION WHEN duplicate_object THEN
      NULL;
    END;
  END IF;
END $$;
