-- BrokerSnapshot API monitoring: sync runs, per-client API logs, cancellation suggestions.
-- Requires auth.users (Supabase default). Bootstraps client_insurance if migration 008 was not run yet.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Bootstrap client_insurance when missing (full app still needs migrations 008–033 for RLS/realtime).
CREATE TABLE IF NOT EXISTS public.client_insurance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  client TEXT NOT NULL,
  mc TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'OK',
  expiration_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.client_insurance
  ADD COLUMN IF NOT EXISTS dot TEXT NOT NULL DEFAULT '';
ALTER TABLE public.client_insurance
  ADD COLUMN IF NOT EXISTS last_cancellation_date DATE;
ALTER TABLE public.client_insurance
  ADD COLUMN IF NOT EXISTS brokersnapshot_last_checked_at TIMESTAMPTZ;

COMMENT ON COLUMN public.client_insurance.brokersnapshot_last_checked_at IS
  'Last time this record was checked via BrokerSnapshot API sync.';

CREATE INDEX IF NOT EXISTS idx_client_insurance_owner_id ON public.client_insurance (owner_id);
CREATE INDEX IF NOT EXISTS idx_client_insurance_status ON public.client_insurance (status);

DROP TRIGGER IF EXISTS client_insurance_updated_at ON public.client_insurance;
CREATE TRIGGER client_insurance_updated_at
  BEFORE UPDATE ON public.client_insurance
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.client_insurance ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'client_insurance' AND policyname = 'client_insurance_select'
  ) THEN
    CREATE POLICY "client_insurance_select" ON public.client_insurance FOR SELECT
      USING (owner_id = auth.uid() OR owner_id IS NULL);
    CREATE POLICY "client_insurance_insert" ON public.client_insurance FOR INSERT
      WITH CHECK (owner_id = auth.uid() OR owner_id IS NULL);
    CREATE POLICY "client_insurance_update" ON public.client_insurance FOR UPDATE
      USING (owner_id = auth.uid() OR owner_id IS NULL)
      WITH CHECK (true);
    CREATE POLICY "client_insurance_delete" ON public.client_insurance FOR DELETE
      USING (owner_id = auth.uid() OR owner_id IS NULL);
  END IF;
END $$;

-- One row per daily or manual sync run.
CREATE TABLE IF NOT EXISTS public.brokersnapshot_sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'partial', 'failed')),
  trigger_source TEXT NOT NULL DEFAULT 'cron'
    CHECK (trigger_source IN ('cron', 'manual')),
  clients_checked INTEGER NOT NULL DEFAULT 0,
  cancellations_found INTEGER NOT NULL DEFAULT 0,
  errors_count INTEGER NOT NULL DEFAULT 0,
  error_summary TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_brokersnapshot_sync_runs_started_at
  ON public.brokersnapshot_sync_runs (started_at DESC);

-- One row per API call during a sync run.
CREATE TABLE IF NOT EXISTS public.brokersnapshot_api_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_run_id BIGINT NOT NULL REFERENCES public.brokersnapshot_sync_runs(id) ON DELETE CASCADE,
  client_insurance_id BIGINT REFERENCES public.client_insurance(id) ON DELETE SET NULL,
  owner_id UUID,
  client_name TEXT,
  mc TEXT,
  dot TEXT,
  request_path TEXT,
  http_status INTEGER,
  success BOOLEAN NOT NULL DEFAULT false,
  error_message TEXT,
  response_summary JSONB,
  cancellation_detected BOOLEAN NOT NULL DEFAULT false,
  cancellation_date DATE,
  duration_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_brokersnapshot_api_logs_sync_run_id
  ON public.brokersnapshot_api_logs (sync_run_id);
CREATE INDEX IF NOT EXISTS idx_brokersnapshot_api_logs_created_at
  ON public.brokersnapshot_api_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_brokersnapshot_api_logs_client_insurance_id
  ON public.brokersnapshot_api_logs (client_insurance_id);

-- Pending cancellation suggestions requiring manual approval.
CREATE TABLE IF NOT EXISTS public.brokersnapshot_cancellation_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_run_id BIGINT REFERENCES public.brokersnapshot_sync_runs(id) ON DELETE SET NULL,
  client_insurance_id BIGINT NOT NULL REFERENCES public.client_insurance(id) ON DELETE CASCADE,
  owner_id UUID,
  client_name TEXT,
  mc TEXT,
  suggested_cancellation_date DATE NOT NULL,
  suggested_dot TEXT,
  policy_number TEXT,
  insurance_company TEXT,
  source_data JSONB,
  review_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (review_status IN ('pending', 'approved', 'rejected', 'superseded')),
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  review_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_brokersnapshot_suggestions_review_status
  ON public.brokersnapshot_cancellation_suggestions (review_status);
CREATE INDEX IF NOT EXISTS idx_brokersnapshot_suggestions_client_insurance_id
  ON public.brokersnapshot_cancellation_suggestions (client_insurance_id);
CREATE INDEX IF NOT EXISTS idx_brokersnapshot_suggestions_created_at
  ON public.brokersnapshot_cancellation_suggestions (created_at DESC);

-- RLS
ALTER TABLE public.brokersnapshot_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brokersnapshot_api_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brokersnapshot_cancellation_suggestions ENABLE ROW LEVEL SECURITY;

-- Helper: can the current user see a client_insurance row?
-- Uses dynamic SQL so team_members / linked_owner_ids are only queried when they exist.
CREATE OR REPLACE FUNCTION public.brokersnapshot_can_access_client_insurance(p_client_insurance_id BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  allowed BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM public.client_insurance ci
    WHERE ci.id = p_client_insurance_id
      AND (ci.owner_id = auth.uid() OR ci.owner_id IS NULL)
  ) INTO allowed;
  IF allowed THEN
    RETURN true;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'team_members'
  ) THEN
    EXECUTE $sql$
      SELECT EXISTS (
        SELECT 1
        FROM public.client_insurance ci
        WHERE ci.id = $1
          AND ci.owner_id IN (
            SELECT tm.owner_id FROM public.team_members tm WHERE tm.member_id = auth.uid()
          )
      )
    $sql$ INTO allowed USING p_client_insurance_id;
    IF allowed THEN
      RETURN true;
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_proc p
    JOIN pg_namespace n ON p.pronamespace = n.oid
    WHERE n.nspname = 'public' AND p.proname = 'linked_owner_ids'
  ) THEN
    EXECUTE $sql$
      SELECT EXISTS (
        SELECT 1
        FROM public.client_insurance ci
        WHERE ci.id = $1
          AND ci.owner_id IN (SELECT public.linked_owner_ids())
      )
    $sql$ INTO allowed USING p_client_insurance_id;
    IF allowed THEN
      RETURN true;
    END IF;
  END IF;

  RETURN false;
END;
$$;

DROP POLICY IF EXISTS "brokersnapshot_sync_runs_select" ON public.brokersnapshot_sync_runs;
CREATE POLICY "brokersnapshot_sync_runs_select" ON public.brokersnapshot_sync_runs
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "brokersnapshot_api_logs_select" ON public.brokersnapshot_api_logs;
CREATE POLICY "brokersnapshot_api_logs_select" ON public.brokersnapshot_api_logs
  FOR SELECT TO authenticated
  USING (
    client_insurance_id IS NULL
    OR owner_id = auth.uid()
    OR public.brokersnapshot_can_access_client_insurance(client_insurance_id)
  );

DROP POLICY IF EXISTS "brokersnapshot_suggestions_select" ON public.brokersnapshot_cancellation_suggestions;
CREATE POLICY "brokersnapshot_suggestions_select" ON public.brokersnapshot_cancellation_suggestions
  FOR SELECT TO authenticated
  USING (
    owner_id = auth.uid()
    OR public.brokersnapshot_can_access_client_insurance(client_insurance_id)
  );

DROP POLICY IF EXISTS "brokersnapshot_suggestions_update" ON public.brokersnapshot_cancellation_suggestions;
CREATE POLICY "brokersnapshot_suggestions_update" ON public.brokersnapshot_cancellation_suggestions
  FOR UPDATE TO authenticated
  USING (public.brokersnapshot_can_access_client_insurance(client_insurance_id))
  WITH CHECK (public.brokersnapshot_can_access_client_insurance(client_insurance_id));

-- Service role bypasses RLS for edge function writes (no INSERT policies for authenticated).
